import os
import sys
# Add backend to path
sys.path.append(os.path.join(os.getcwd(), 'backend'))

from sqlalchemy import create_engine, text
from backend.core.config import settings

def check_db():
    print(f"Connecting to {settings.DATABASE_URL}")
    engine = create_engine(settings.DATABASE_URL)
    with engine.connect() as connection:
        result = connection.execute(text("SELECT table_name FROM information_schema.tables WHERE table_schema='public'"))
        tables = [row[0] for row in result]
        print("Tables:", tables)
        
        # Check if Chat table exists
        if 'Chat' in tables or 'chat' in tables:
            print("Chat table found.")
            # Create a dummy chat
            try:
                # UUID is generated by default? No, schema says @default(uuid())
                # But we are using raw sql or sqlalchemy?
                # Let's try raw insert to be sure
                insert_query = text("INSERT INTO \"Chat\" (id, title, \"userId\", \"updatedAt\") VALUES ('123e4567-e89b-12d3-a456-426614174000', 'Test Chat', 'test-user', NOW()) ON CONFLICT (id) DO NOTHING RETURNING id")
                result = connection.execute(insert_query)
                connection.commit()
                print("Dummy chat created/verified with ID: 123e4567-e89b-12d3-a456-426614174000")
            except Exception as e:
                print(f"Error creating dummy chat: {e}")
        else:
            print("Chat table NOT found.")

if __name__ == "__main__":
    check_db()
